export const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM',
  DECREASE_ONE_POSITION_FROM_CART_ITEM: 'DECREASE_ONE_POSITION_FROM_CART_ITEM'
};
